### ISSUE TITLE
Explore use of Mozilla Persona to enable user signon without storing passwords.

### ISSUE THREAD

**Issue by karger** [nbproject/nbproject#188]
Persona looks like a good choice to let us stop worrying about passwords on our site, and also puts us on the side of the angels. https://developer.mozilla.org/en-US/Persona
Would someone like to test the following claim #3 from the page:
Persona is easy to implement. Developers can add Persona to a site in a single afternoon.

Key question: is persona widely deployed and robust enough that we can trust it to work and keep working for the foreseeable future?

**Comment by kesiena115** [comment]
We need to close this issue. According to their website:

> Persona is no longer actively developed by Mozilla. Mozilla has committed to operational and security support of the persona.org services until November 30th, 2016.
> 
> On November 30th, 2016, Mozilla will shut down the persona.org services. Persona.org and related domains will be taken offline.
