### ISSUE TITLE
tuple required for TEMPLATE_DIRS setting

### ISSUE THREAD

**Issue by ururk** [nbproject/nbproject#202]
I think this is a bug. I'm using the latest django (1.7.3) on a clean ubuntu install. Running the app, apache throws this error:

    ImproperlyConfigured: The TEMPLATE_DIRS setting must be a tuple. Please fix your settings.

Adding parens around the configuration setting fixes the problem:

    TEMPLATE_DIRS = (
        # Put strings here, like "/home/html/django_templates" or "C:/www/django/templates".
        # Always use forward slashes, even on Windows.
        # Don't forget to use absolute paths, not relative paths.
        (abspath("%s/../../templates" % (ROOTDIR, ))),
    )

**Comment by karger** [comment]
Resolved in d3f2c53
