### ISSUE TITLE
Time on client side-side JS not generated consistently

### ISSUE THREAD

**Issue by ururk** [nbproject/nbproject#206]
DB stores time in UTC, and UTC time is sent to the client. When the client calls .toPrettyString(), if it isn't the current day/time, it is displayed in UTC. Otherwise, it is displayed in the local user's timezone.

https://github.com/nbproject/nbproject/blob/162e67e0fa8ff83015d2967015e700ea4df49408/content/modules/dateformat/date.format.js#L149

```js
Date.prototype.toPrettyString = function () {
        var current_date = new Date();

        if (this.getFullYear() !== current_date.getFullYear()) { // Not even this year
            return this.format("d mmm yyyy", true);
        } else if (this.getWeek() !== current_date.getWeek()) { // This year but not this week
            return this.format("d mmm, hh:MMTT", true);
        } else if (this.getDay() !== current_date.getDay()) { // This week but not today
            return this.format("ddd hh:MMTT", true);
        }

        // Today
        return this.format("hh:MMTT");
};
```

To be consistent, either the default return value should include true:

```js
return this.format("hh:MMTT", true);
```

or remove `, true` from the other return values. The easiest way to see whether this change is correct, is to add ` Z` to the date format string for each format string to see what it generates. I didn't do a pull request for this as I haven't done a lot of testing across multiple timezone configurations (mine is set to America / Detroit), but I know for my configuration this seems to be the case, as well as some limited testing with timestamps that I've done.

**Comment by ururk** [comment]
Also - this effects anything that uses toPrettyString - so `content/modules/dev/ui.threadview.js`  and `content/modules/dev/ui.notepaneView.spreadsheet.js `

**Comment by karger** [comment]
It's pretty obvious that you've found a bug that should be fixed, even if it isn't the bug you were looking for (someone else just reported the same problem).  `true` should be added as an argument in the final, default case (it was intentionally added in all the other lines, but they forgot the last one).  Please submit a pull request, and we'll work on incorporating it into the main branch quickly.

**Comment by ururk** [comment]
Ok - I wasn't sure what the desired behavior was (`, true` or leave it off). It seems that if instructors are in EDT, but the time reported to them is in UTC, if they are using those times for assignment due dates, the time would be off by 5 hours (or whatever their timezone was). Without TZ notation, they will have to mentally adjust the reported time, and unless they are testing they may not notice that the posted time is in UTC.

**Comment by karger** [comment]
Yes, I think instructors should get info reported in their own timezone, 
and I thought that's what adding the "true" argument would provide?

**Comment by ururk** [comment]
Not in my testing - `true` returns a UTC time. Because of the current bug, if you are testing and checking a new post, it will first return `this.format("hh:MMTT");` in the current local time, but on older dates it will return a format with `true` set and the time returned is in UTC. See:

http://jsfiddle.net/ururk/hr781pt6/

This has the unmodified time code, and some JSON with ctime/created from my nb install. Try different timestamps. I often use `http://www.epochconverter.com` as a sanity check or to generate timestamps. Also try adding `Z` to the formats that `toPrettyString()` uses.

**Comment by karger** [comment]
That's interesting.  I'm going to see if I can find out why my student 
switched things to default to utc.

**Comment by Eyas** [comment]
Hi all, the change to use `true` was done in 5080ea5e. You are right that there is an inconsistency between the `"hh:MMTT"` case and the others. That should be resolved.

This was in flux when we moved to use timezone aware times in Django, which should be returning the time in UTC. I think an intermediate implementation included converting to local time on the server and adding `, true` to all.

Definitely a bug, I'll make a quick fix.

**Comment by karger** [comment]
Thanks very much Eyas!  Are we now using UTC consistently on the server, 
so that we should be assuming client-side conversaion at all times?

**Comment by Eyas** [comment]
Yeah, that is correct. UTC *should* be used consistently on the server. I'll make the commit on the master branch since it is a safe one. I don't want to force anyone to pull from dev or anything else to apply this simple change. Does that sound like a plan?

**Comment by karger** [comment]
yes; this is a good plan.
do you also know how to *deploy* from that commit?  Sacha is far behind 
due to the blizzard and might not be able to get to it soon.

**Comment by Eyas** [comment]
Unfortunately, I believe I lost my certificate credentials after graduation so will be unable to deploy.. I'm also not sure what branch the main site is on, so I might mess something up by pulling the wrong branch even if I did!
