### ISSUE TITLE
Failed video uploads shouldn't add "dead" video links to class

### ISSUE THREAD

**Issue by karger** [nbproject/nbproject#212]
Right now, when an attempt to upload a video to nb fails, it produces a "dead" (nonplayable, untitled) video object in the class content.  It shouldn't (issue #211).

**Comment by karger** [comment]
I don't think the submitted code fixes this issue.  I could give some other kind of broken url (ie not a youtu.be link) and it will still give me a dead link.

**Comment by sachazyto** [comment]
sure, this is just the quick fix we mentioned in order to accomodate for 
youtu.be urls. Note that a proper fix should probably move the handling 
code in the youtube form.
