### ISSUE TITLE
Javascript code in html templates

### ISSUE THREAD

**Issue by karger** [nbproject/nbproject#271]
At least one of our apps html templates (namely templates/web/source_analytics.html) contains a large amount of javascript.  This seems a bad programming practice, not least because the html filetype means your editor/ide won't properly indent or syntax-highlight the javascript.  The JS should be moved to a suitable file (where it can combined minified/packaged during compilation) and then referenced/fetched by the html file.

**Comment by kesiena115** [comment]
Fixed the analytics page in this pull request: https://github.com/nbproject/nbproject/pull/328
