### ISSUE TITLE
Analytics image thumbnails are broken

### ISSUE THREAD

**Issue by karger** [nbproject/nbproject#272]
Page images are showing up as broken links on the "Analytics" page associated with a pdf document.  The error log shows problems with mudraw, e.g.
`[Mon Jan 04 09:45:30.061672 2016] [:error] [pid 23272:tid 140256208660224] (mudraw -o /var/local/nb_karger/Ubuntu/pdf/cache2/288/33/5_0002.png -r 95 -b 8 /var/local/nb_karger/Ubuntu/pdf/repository/5 3) && (echo)`
which means the necessary thumbnail images are not being generated.

**Comment by kesiena115** [comment]
Fixed
