### ISSUE TITLE
Adding comment not working on Youtube video

### ISSUE THREAD

**Issue by sachazyto** [nbproject/nbproject#299]
Tested on Chrome for linux. I'm getting the following error
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

**Comment by karger** [comment]
master or dev?

**Comment by sachazyto** [comment]
Master

**Comment by karger** [comment]
probably an inconsistency between the dev and master db schemas (which I
thought did not exist).  I've rolled master forward to dev to see if
that fixes the problem.

**Comment by sachazyto** [comment]
yay, it works. Thanks a lot.
