### ISSUE TITLE
wrong URL when registering as guest

### ISSUE THREAD

**Issue by sachazyto** [nbproject/nbproject#6]
If the URL that was being visited when a guest decided to register already has query parameters (e.g. ?p=1), then the link sent to the guest is wrong (it's http://servername?p=1?ckey=... when it should be http://servername?p=1&ckey=...

**Comment by kesiena115** [comment]
It looks like we no longer include the ckey in URLs so I believe this bug no longer exists (I checked a URL that had a query parameter).
