### ISSUE TITLE
Separate registration from invitation

### ISSUE THREAD

**Issue by karger** [nbproject/nbproject#77]
Our current model mixes the process of someone getting an nb account from the process of giving access to a class: faculty invitations simultaneously allow a student to register an email and give them access to a class.  We don't need faculty invites to permit the first step (registration).  We should let anyone register an email address (by sending a confirmation email to their address that lets them set their password).  Faculty invitations to a class should instead be simply a *permissions* issue.  We can send a notification to students who are not yet registered, but even if they don't get it, they should be able to register themselves, then get access to the course on the basis of the faculty having given permission to the student's email---even if the permission was granted before the student registered the email.

**Comment by kesiena115** [comment]
The new navbar makes it possible to register without class invitation
