### ISSUE TITLE
"no" is displayed twice on "Add a new class" dialog

### ISSUE THREAD

**Issue by sachazyto** [nbproject/nbproject#96]
![screen shot 2013-04-30 at 12 48 31 pm](https://f.cloud.github.com/assets/618189/445194/4d1fb0b4-b1b6-11e2-9e0e-aa36ec61bcdc.png)
cf sceenshot.

**Comment by sachazyto** [comment]
reopening: the questions are being asked twice now. The second time. the "no" is repeated.

**Comment by kesiena115** [comment]
Fixed in https://github.com/nbproject/nbproject/pull/324
